#!/bin/sh

### BEGIN INIT INFO
# Provides: jsbin (via node)
# Required-Start: $local_fs $remote_fs $network $named $syslog
# Required-Stop: $local_fs $remote_fs $network $named $syslog
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start, stop, get status from and restart jsbin
# Description: Start, stop, get status from and restart jsbin
### END INIT INFO

# run update-rc.d to create the proper links to rc*.d directories
 
APP=jsbin
USER=jsbin

APP_HOME=/srv/node/jsbin

export FOREVER_ROOT=/etc/forever

case "$1" in 
# Start command 
start) 
echo "Starting $APP" 
/bin/su -m $USER -c "$APP_HOME/contrib/script/startup-shutdown.sh start"
;;

# Stop command 
stop) 
echo "Stopping $APP" 
/bin/su -m $USER -c "$APP_HOME/contrib/script/startup-shutdown.sh stop"
echo "$APP stopped successfully" 
;;

# Status command
status)
echo "Getting status for $APP"
/bin/su -m $USER -c "$APP_HOME/contrib/script/startup-shutdown.sh status"
;;

# Restart command 
restart) 
$0 stop 
sleep 10
$0 start 
;;
 
*) 
echo "Usage: /etc/init.d/$APP {start|restart|status|stop}" 
exit 1 
;;
 
esac 

exit 0
